JobPortal/Controllers/ProviderController.cs
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using JobPortal.Data;
using JobPortal.Models;
using JobPortal.Services;
using JobPortal.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace JobPortal.Controllers
{
    [Authorize(Roles = "JobProvider")]
    public class ProviderController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly ApplicationDbContext _context;
        private readonly IJobRepository _jobRepository;
        private readonly IApplicantRepository _applicantRepository;

        public ProviderController(UserManager<IdentityUser> userManager,
            ApplicationDbContext context,
            IJobRepository jobRepository,
            IApplicantRepository applicantRepository)
        {
            _context = context;
            _userManager = userManager;
            _jobRepository = jobRepository;
            _applicantRepository = applicantRepository;
        }

        public IActionResult Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View(_jobRepository.GetJobByProviderId(userId));
        }

        [HttpGet]
        public IActionResult AddJob()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddJob(AddJobViewModel model)
        {
            if (ModelState.IsValid)
            {
                var job = new Jobs
                {
                    JobId = Guid.NewGuid().ToString(),
                    Active = true,
                    Location = model.Location,
                    Company = model.Company,
                    Salary = model.Salary,
                    ProviderId = User.FindFirstValue(ClaimTypes.NameIdentifier),
                    ToolsAndTechnologies = model.ToolsAndTechnologies
                };
                _context.Add(job);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        public async Task<IActionResult> ListApplicant(string jobid)
        {
            var job = _jobRepository.GetJobById(jobid);
            if (job == null || job.ProviderId != User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                Response.Redirect("/Identity/Account/AccessDenied");
            }

            List<Applicant> applicants = _applicantRepository.GetApplicantByJobId(jobid);
            List<ListApplicantViewModel> model = new List<ListApplicantViewModel>();
            if (applicants != null)
            {
                foreach (var applicant in applicants)
                {
                    var user = await _userManager.FindByIdAsync(applicant.UserId);
                    model.Add(new ListApplicantViewModel
                    {
                        ResumeLink = applicant.ResumeLink,
                        Email = user.Email
                    });
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> UpdateJob(string? jobid)
        {
            if (jobid == null)
            {
                return NotFound();
            }

            var job = await _context.Jobs.FindAsync(jobid);
            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        [HttpPost]
        public async Task<IActionResult> UpdateJob(string jobid,
            [Bind("JobId, Active, Location, Company, Salary, ToolsAndTechnologies, ProviderId")]
            Jobs job)
        {
            if (jobid != job.JobId || job.ProviderId != User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Update(job);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(job);
        }

        public async Task<IActionResult> CloseApplications()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View(await _context.Jobs.Where(x => x.ProviderId == userId && x.Active).ToListAsync());
        }

        public async Task<IActionResult> Close(string jobid)
        {
            var job = await _context.Jobs.FindAsync(jobid);
            if (job == null || job.ProviderId != User.FindFirstValue(ClaimTypes.NameIdentifier))
            {
                return NotFound();
            }

            job.Active = false;

            _context.Update(job);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

JobPortal/Controllers/SeekerController.cs
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using JobPortal.Data;
using JobPortal.Models;
using JobPortal.Services;
using JobPortal.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace JobPortal.Controllers
{
    [Authorize(Roles = "JobSeeker")]
    public class SeekerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IJobRepository _jobRepository;

        public SeekerController(
            ApplicationDbContext context,
            IJobRepository jobRepository)
        {
            _context = context;
            _jobRepository = jobRepository;
        }

        public async Task<IActionResult> Index()
        {
            var applicants = await _context.Applicants
                .Where(x => x.UserId == User.FindFirstValue(ClaimTypes.NameIdentifier)).ToListAsync();
            return View(_context.Jobs.AsEnumerable()
                .Where(x => x.Active == true && applicants.All(y => y.JobId != x.JobId)).ToList());
        }

        [HttpGet]
        public IActionResult Apply(string jobid)
        {
            var job = _jobRepository.GetJobById(jobid);
            if (job == null)
            {
                return NotFound();
            }

            var model = new ApplyJobViewModel
            {
                JobId = jobid
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Apply(ApplyJobViewModel model)
        {
            if (ModelState.IsValid)
            {
                var job = _jobRepository.GetJobById(model.JobId);
                if (job == null)
                {
                    return NotFound();
                }

                var applicant = new Applicant
                {
                    JobId = model.JobId,
                    UserId = User.FindFirstValue(ClaimTypes.NameIdentifier),
                    ResumeLink = model.ResumeLink
                };
                _context.Add(applicant);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        public async Task<IActionResult> ListJobs()
        {
            var applicants = await _context.Applicants
                .Where(x => x.UserId == User.FindFirstValue(ClaimTypes.NameIdentifier)).ToListAsync();
            return View(_context.Jobs.AsEnumerable().Where(x => applicants.Any(y => y.JobId == x.JobId)).ToList());
        }
    }
}

JobPortal/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>JobPortal</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="~/assets/css/styles.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.2.0/aos.css">
</head>

<body>
<nav class="navbar navbar-light navbar-expand-md navigation-clean">
    <div class="container">
        <a class="navbar-brand" href="#">Job Portal</a>
        <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1">
            <span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse"
             id="navcol-1">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item" role="presentation">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link" asp-controller="Home" asp-action="Privacy">Privacy Policy</a>
                </li>
                <li class="nav-item" role="presentation">
                    <a class="nav-link" asp-controller="Home" asp-action="Aboutus">About Us</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">
                        <i class="fa fa-group"></i>
                    </a>
                    <div class="dropdown-menu" role="menu">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            @if (User.IsInRole("JobSeeker"))
                            {
                                <form class="form-inline" asp-controller="Seeker" asp-action="Index">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Go Back</button>
                                </form>                            }
                            @if (User.IsInRole("JobProvider"))
                            {
                                <form class="form-inline" asp-controller="Provider" asp-action="Index">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Go Back</button>
                                </form>                            }
                            @if (User.IsInRole("Admin"))
                            {
                                <form class="form-inline" asp-controller="Admin" asp-action="Index">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Go Back</button>
                                </form>
                            }
                            <form class="form-inline" method="post" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new {area = ""})">
                                <button type="submit" class="nav-link btn btn-link text-dark">Logout(@User.Identity.Name)</button>
                            </form>                            
                        }
                        else
                        {
                            <a class="dropdown-item" role="presentation" asp-area="Identity" asp-page="/Account/Login">Login</a>
                            <a class="dropdown-item" role="presentation" asp-area="Identity" asp-page="/Account/Register">Register</a>                            
                        }
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
@RenderBody()
<div class="footer-basic">
    <footer>
        <ul class="list-inline">
            <li class="list-inline-item">
                <a asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="list-inline-item"></li>
            <li class="list-inline-item">
                <a asp-controller="Home" asp-action="Privacy">Privacy Policy</a>
            </li>
            <li class="list-inline-item"></li>
            <li class="list-inline-item">
                <a asp-controller="Home" asp-action="Contactus">Contact Us</a>
            </li>
        </ul>
        <p class="copyright">Job Portal © 2020</p>
    </footer>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.2.0/aos.js"></script>
<script src="~/assets/js/script.min.js"></script>
@RenderSection("Scripts", required: false)
</body>

</html>